### PR TITLE
Upgrading Nginx to 1.10.1

### PR DESCRIPTION
**Pull request by HemantErappa**
Upgrading Nginx to 1.10.1
Fixing compilation errors during upgrade

@juanman2 @levb @krobertson @Kusanagi9999 

Fixes #ENGT-7156

### CODE REVIEW

**Comment by Kusanagi9999** [comment]
LGTM on green.

**Comment by Kusanagi9999** [comment]
Noticed the following comment in Lev's PR
> Still WIP, pending other nginx build changes on the same-named branches of continuum, continuum-workspace

So, we don't need changes in continuum and continuum-workspace for this upgrade after all?

**Comment by HemantErappa** [comment]
Lev was planning additional tasks like moving Nginx build from continuum
build script, etc.  I am not doing all that.

Hemant

**Comment by Kusanagi9999** [comment]
It is probably also a good idea to run the router system tests in a loop 50 times.

**Comment by Kusanagi9999** [comment]
LGTM on green AWS/VSphere.

**Comment by Kusanagi9999** [comment]
Regex tests passed: http://tc.apcera.net/viewLog.html?buildId=174557&buildTypeId=SystemTestsApceraSetup_DeployTestBranchesRegexp&tab=testsInfo

**Pull request merged**
